name: 🏗️ Epic
description: Create a new epic for major feature development
title: "[EPIC] "
labels: ["epic", "needs-triage"]
assignees:
  - lraunakl
body:
  - type: markdown
    attributes:
      value: |
        ## Epic Overview
        An epic represents a large body of work that can be broken down into multiple user stories. Use this template to define major features or capabilities.
        
  - type: input
    id: epic-title
    attributes:
      label: Epic Title
      description: A clear, concise title for this epic
      placeholder: e.g., "User Authentication System"
    validations:
      required: true
      
  - type: textarea
    id: epic-description
    attributes:
      label: Epic Description
      description: Detailed description of what this epic aims to achieve
      placeholder: |
        Provide a comprehensive overview of the epic including:
        - What problem it solves
        - Who benefits from it
        - High-level scope
      render: markdown
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Business priority of this epic
      options:
        - High (Must Have)
        - Medium (Should Have)
        - Low (Could Have)
    validations:
      required: true
      
  - type: dropdown
    id: story-points
    attributes:
      label: Story Points Estimate
      description: Estimated complexity using Fibonacci sequence
      options:
        - "1 (XS - Trivial)"
        - "3 (S - Small)"
        - "5 (M - Medium)"
        - "8 (L - Large)"
        - "13 (XL - Very Large)"
        - "21 (XXL - Extra Large)"
        - "34 (XXXL - Needs Breaking Down)"
        - "55+ (Break into smaller epics)"
    validations:
      required: true
      
  - type: textarea
    id: user-stories
    attributes:
      label: User Stories Breakdown
      description: List of user stories that make up this epic
      placeholder: |
        - [ ] As a user, I want to register an account so that I can access the platform
        - [ ] As a user, I want to log in with my credentials so that I can access my account
        - [ ] As a user, I want to reset my password so that I can recover access to my account
      render: markdown
    validations:
      required: true
      
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Epic Acceptance Criteria
      description: High-level criteria that must be met for this epic to be considered complete
      placeholder: |
        - [ ] All user stories in this epic are completed and tested
        - [ ] Security requirements are met
        - [ ] Performance benchmarks are achieved
        - [ ] Documentation is updated
        - [ ] Code follows project standards
      render: markdown
    validations:
      required: true
      
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Other epics or external dependencies required for this work
      placeholder: |
        **Internal Dependencies:**
        - Epic #X: Foundation setup must be complete
        
        **External Dependencies:**
        - Third-party API integration
        - Design system components
      render: markdown
      
  - type: dropdown
    id: target-sprint
    attributes:
      label: Target Sprint/Milestone
      description: When do you plan to work on this epic?
      options:
        - Sprint 1
        - Sprint 2
        - Sprint 3
        - Sprint 4
        - Sprint 5
        - Sprint 6
        - Future Release
        - TBD
    validations:
      required: true
      
  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Considerations
      description: Technical implementation notes, architecture decisions, or constraints
      placeholder: |
        **Architecture:**
        - Database schema changes required
        - New API endpoints needed
        
        **Technology Stack:**
        - Node.js/Express for backend
        - MongoDB for data persistence
        
        **Security:**
        - JWT token implementation
        - Password hashing with bcrypt
      render: markdown
      
  - type: textarea
    id: definition-of-done
    attributes:
      label: Definition of Done
      description: Specific criteria for considering this epic complete
      placeholder: |
        - [ ] All user stories pass acceptance testing
        - [ ] Unit test coverage >= 80%
        - [ ] Integration tests written and passing
        - [ ] Security review completed
        - [ ] Performance testing completed
        - [ ] Documentation updated (API docs, user guides)
        - [ ] Code review approved
        - [ ] Deployed to staging environment
        - [ ] Stakeholder approval received
      render: markdown
    validations:
      required: true
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information (mockups, research, constraints)
      placeholder: |
        **Research:**
        - Link to user research findings
        - Competitive analysis
        
        **Design:**
        - Figma mockups
        - User flow diagrams
        
        **Constraints:**
        - Budget limitations
        - Timeline restrictions
      render: markdown
